<a href="https://colab.research.google.com/github/TabatHaru/EU_M_Math-Repository/blob/main/Chap05_Ex_01_02_03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [98]:
import numpy as np
import numpy.random as random
import scipy as sp

import matplotlib.pyplot as plt
import matplotlib as mpl
%matplotlib inline

%precision 3

'%.3f'

In [ ]:
sample_array = np.arange(10)
print('sample_array',sample_array)

sample_array [0 1 2 3 4 5 6 7 8 9]


In [ ]:
print(sample_array)

sample_array_slice = sample_array[0:5]
print(sample_array_slice)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4]


In [ ]:
sample_array_slice[0:3] = 10
print(sample_array_slice)

print(sample_array)

[10 10 10  3  4]
[10 10 10  3  4  5  6  7  8  9]


In [ ]:
sample_array_copy = np.copy(sample_array)
print(sample_array_copy)

sample_array_copy[0:3] = 20
print(sample_array_copy)

print(sample_array)

[10 10 10  3  4  5  6  7  8  9]
[20 20 20  3  4  5  6  7  8  9]
[10 10 10  3  4  5  6  7  8  9]


In [99]:
sample_names = np.array(['a','b','c','d','a'])
random.seed(0)
data = random.randn(5,5)

print(sample_names)
print(data)

TypeError: 'numpy.ndarray' object is not callable

In [ ]:
sample_names == 'a'

array([ True, False, False, False,  True])

In [ ]:
data[sample_names =='a']

array([[ 1.764,  0.4  ,  0.979,  2.241,  1.868],
       [-2.553,  0.654,  0.864, -0.742,  2.27 ]])

In [ ]:
cond_data = np.array([True,True,False,False,True])

x_array = np.array([1,2,3,4,5])

y_array = np.array([100, 200, 300, 400, 500])

print(np.where(cond_data,x_array,y_array))


TypeError: 'numpy.ndarray' object is not callable

In [ ]:
# Practice_Ex_5-1
sample_names = np.array(['a', 'b', 'c', 'd', 'a'])
random.seed(0)
data = random.randn(5,5)

print(sample_names)
print(data)
data[sample_names=='b']

TypeError: 'numpy.ndarray' object is not callable

In [ ]:
# Practice_Ex_5-2
data[sample_names != 'c']

array([[ 1.764,  0.4  ,  0.979,  2.241,  1.868],
       [-0.977,  0.95 , -0.151, -0.103,  0.411],
       [ 0.334,  1.494, -0.205,  0.313, -0.854],
       [-2.553,  0.654,  0.864, -0.742,  2.27 ]])

In [ ]:
# Practice_Ex_5-3
x_array = np.array([1,2,3,4,5])
y_array = np.array([6,7,8,9,10])

cond_data = np.array([False,False,True,True,False])

print(np.where(cond_data, x_array, y_array))

[ 6  7  3  4 10]


In [ ]:
cond_data = np.array([True,True,False,False,True])

print(cond_data)
#重複削除
print(np.unique(cond_data))

[ True  True False False  True]
[False  True]


In [ ]:
sample_data = np.arange(10)
print('元のデータ :', sample_data)
print('すべての要素の平方根 :', np.sqrt(sample_data))
print('すべての要素のネイピア指数関数 :',np.exp(sample_data))

元のデータ : [0 1 2 3 4 5 6 7 8 9]
すべての要素の平方根 : [0.    1.    1.414 1.732 2.    2.236 2.449 2.646 2.828 3.   ]
すべての要素のネイピア指数関数 : [1.000e+00 2.718e+00 7.389e+00 2.009e+01 5.460e+01 1.484e+02 4.034e+02
 1.097e+03 2.981e+03 8.103e+03]


In [ ]:
sample_multi_array_datal = np.arange(9).reshape(3,3)
print(sample_multi_array_datal)

print('最小値 :', sample_multi_array_datal.min())
print('最大値 :', sample_multi_array_datal.max())
print('平均 :', sample_multi_array_datal.mean())
print('合計 :', sample_multi_array_datal.sum())

print('行の合計 :', sample_multi_array_datal.sum(axis=1))
print('列の合計 :', sample_multi_array_datal.sum(axis=0))

[[0 1 2]
 [3 4 5]
 [6 7 8]]
最小値 : 0
最大値 : 8
平均 : 4.0
合計 : 36
行の合計 : [ 3 12 21]
列の合計 : [ 9 12 15]


In [ ]:
cond_data = np.array([True,True,False,False,True])

print('Trueが少なくとも1つあるかどうか :',cond_data.any())
print('すべてTrueかどうか :', cond_data.all())

TypeError: 'numpy.ndarray' object is not callable

In [ ]:
sample_multi_array_datal = np.arange(9).reshape(3,3)
print(sample_multi_array_datal)
print('5より大きい数字がいくつあるか :', (sample_multi_array_datal>5).sum())

[[0 1 2]
 [3 4 5]
 [6 7 8]]
5より大きい数字がいくつあるか : 3


In [ ]:
sample_multi_array_datal = np.arange(9).reshape(3,3)
print(sample_multi_array_datal)

print('対角成分 :',np.diag(sample_multi_array_datal))
print('対角成分の和 :',np.trace(sample_multi_array_datal))

[[0 1 2]
 [3 4 5]
 [6 7 8]]
対角成分 : [0 4 8]
対角成分の和 : 12


In [ ]:
# Practice Ex_5-4
sample_multi_array_data2 = np.arange(16).reshape(4,4)
sample_multi_array_data2


print(np.sqrt(sample_multi_array_data2))

[[0.    1.    1.414 1.732]
 [2.    2.236 2.449 2.646]
 [2.828 3.    3.162 3.317]
 [3.464 3.606 3.742 3.873]]


In [ ]:
# Practice Ex_5-5
print('最大値 :',sample_multi_array_data2.max())
print('最小値 :',sample_multi_array_data2.min())
print('合計値 :',sample_multi_array_data2.sum())
print('平均値 :',sample_multi_array_data2.mean())

最大値 : 15
最小値 : 0
合計値 : 120
平均値 : 7.5


In [ ]:
# Practice Ex_5-6
print('対角成分の和 :',np.trace(sample_multi_array_data2))

対角成分の和 : 30


In [ ]:
sample_array = np.arange(10)
sample_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
sample_array2 = sample_array.reshape(2,5)
sample_array2

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [ ]:
sample_array2.reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [ ]:
# 配列を作成
sample_array3 = np.array([[1, 2, 3], [4, 5, 6]])
sample_array4 = np.array([[7, 8, 9], [10, 11, 12]])

# 配列を表示
print(sample_array3)
print(sample_array4)

# 配列を結合
result = np.concatenate([sample_array3, sample_array4], axis=0)
print("Concatenated Array:")
print(result)


TypeError: 'numpy.ndarray' object is not callable

In [ ]:
import numpy as np

# 配列を作成
sample_array3 = np.array([[1, 2, 3], [4, 5, 6]])
sample_array4 = np.array([[7, 8, 9], [10, 11, 12]])

# 配列を表示
print("Array 3:")
print(sample_array3)
print("Array 4:")
print(sample_array4)

# 配列を結合
result = np.concatenate([sample_array3, sample_array4], axis=0)
print("Concatenated Array:")
print(result)


TypeError: 'numpy.ndarray' object is not callable

In [ ]:
np.vstack(sample_array3,sample_array4)

In [ ]:
np.concatenate([sample_array3,sample_array4],axis = 1)

In [ ]:
np.hstack(sample_array3,sample_array4)

In [ ]:
sample_array3 = np.array([[1,2,3],[4,5,6]])
sample_array4 = np.array([[7.8.9],[10,11,12]])
sample_array_vstack = np.vstack((sample_array3,sample_array4))

sample_array_vstack

SyntaxError: invalid syntax. Perhaps you forgot a comma? (<ipython-input-55-8edfe178edbe>, line 2)

In [ ]:
first,second,third=np.split(sample_array_vstack, [1,3])

print(first)

NameError: name 'sample_array_vstack' is not defined

In [ ]:
print(second)

In [ ]:
second[0]

In [ ]:
print(third)

In [ ]:
sample_array5 = np.array([[13.14.15],[16,17,18],[19,20,21]])
sample_array_vstack2 = np.vstack((sample_array3,sample_array4,sample_array5))

print(sample_array_vstack2)

In [ ]:
first,second,third,fouth=np.split(sample_array_vstack2, [2,3,5])

print('・1つ目 :\n',first, '\n')
print('・2つ目 :\n', second, '\n')
print('・3つ目 :\n', third, '\n')
print('・4つ目 :\n', fouth, '\n')

In [ ]:
first[0]

In [ ]:
first[1]

In [ ]:
first.repeat(5)

In [ ]:
sample_array = np.arange(10)
print(sample_array)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
sample_array +3

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
# Practice Ex_5-7
sample_array1 = np.arange(12).reshape(3,4)
sample_array2 = np.arange(12).reshape(3,4)

np.concatenate([sample_array1,sample_array2], axis=0)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
# Practice Ex_5-8
np.concatenate([sample_array1,sample_array2], axis=1)

array([[ 0,  1,  2,  3,  0,  1,  2,  3],
       [ 4,  5,  6,  7,  4,  5,  6,  7],
       [ 8,  9, 10, 11,  8,  9, 10, 11]])

In [ ]:
# Practice Ex_5-9
sample_list = [1,2,3,4,5]

sample_list = np.arange(5)

sample_list +3

array([3, 4, 5, 6, 7])